[agent]
  interval = "10s" # Telegraf controlla i dati ogni 10 secondi
  round_interval = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt-broker:1883"]
  topics = ["sensors/+"]
  data_format = "json"
  tag_keys = ["id"]

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "9UAPy4qDu16TQSUe4G9EN88rzsnC1srqrhgwu4Kxg9asMCxLdkCq_NgZzUp2gpnAfSj5W-XTzjeIUEsA23CiIw=="
  organization = "GreenMoving"
  bucket = "bike_monitoring"

